Test Test (#2)
* Test Test

* Test Test

* Test Test

* Test Test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,11 +3,8 @@ name: "Test"
 on:
   workflow_dispatch:
   push:
-#    branches:
-#      - master
-#  pull_request:
-#    branches:
-#      - master
+    paths:
+      - "src/**"
 
 jobs:
   test:
@@ -28,3 +25,53 @@ jobs:
       - name: "Echo Outputs"
         run: |
           echo '${{ steps.test.outputs.result }}'
+
+  lint:
+    name: "Lint"
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+
+      - name: "Setup Node"
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - name: "ESLint"
+        run: |
+          npm install
+          npm run lint
+
+  build:
+    name: "Build"
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+
+      - name: "Setup Node"
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - name: "Build"
+        run: |
+          npm install
+          npm run build
+
+      - name: "Verify"
+        run: |
+          git status --porcelain dist/
+          if [ ! -d "dist" ];then
+            echo "Missing dist directory, run: npm build"
+            exit 1
+          fi
+          if [ -n "$(git status --porcelain dist)" ];then
+            echo "Build was not run, run: npm build"
+            exit 1
+          fi
